### ISSUE TITLE
Wiki instructions for 2.x.x to 3.x.x is missing

### ISSUE THREAD

**Issue by lpaulger** [damiencaselli/ember-cli-sentry#101]
[Readme.md](https://github.com/damiencaselli/ember-cli-sentry#important-notice-if-you-migrate-from-2xx-to-3x) points to  https://github.com/damiencaselli/ember-cli-sentry/wiki/Migration-from-2.x.x-to-3.x but the documentation is missing

**Comment by mattmcmanus** [comment]
This isn't an easy answer, but here is all that changed from the last 2.x version of the addon: https://github.com/damiencaselli/ember-cli-sentry/compare/2.4.4...3.0.0-beta.1
