### ISSUE TITLE
IE 10 bug with <meta name="sentry:revision"></meta>

### ISSUE THREAD

**Issue by janwerkhoven** [damiencaselli/ember-cli-sentry#104]
IE 10 seems to break when it hits:
```
<meta name="sentry:revision"></meta>
```
![screen shot 2017-10-25 at 2 51 36 pm](https://user-images.githubusercontent.com/4415419/31979929-08341e18-b995-11e7-957f-517f5e1136a4.png)

HTML `<meta>` elements do not require the closing tag `</meta>`. IE 10 finds that so outrageous that it breaks, throws and stop execution of everything that follows 😑 .

This tag is inserted by `ember-cli-sentry` via `{{content-for "head-footer"}}` in the `app/index.html`. Is there anything that you can do to resolve this? What can we do to resolve this?

Thanks!

**Comment by damiencaselli** [comment]
Hey @janwerkhoven, can you confirm on a sample HTML page that not closing a meta tag using an html5 doctype breaks IE10?

**Comment by janwerkhoven** [comment]
This is the screenshot of a user showing an error on IE10 breaking the page:

![screen shot 2017-10-26 at 1 12 30 pm](https://user-images.githubusercontent.com/4415419/32031850-5cc126e6-ba4f-11e7-8416-8a1cfdae6025.png)

The error points at line 57 which is this screenshot:

![screen shot 2017-10-25 at 2 51 36 pm](https://user-images.githubusercontent.com/4415419/31979929-08341e18-b995-11e7-957f-517f5e1136a4.png)

So far I haven't been able to reliably reproduce the bug. When I open up IE10 in Browserstack, no such errors occur, even thought the `</meta>` is present.

![screen shot 2017-10-26 at 12 26 26 pm](https://user-images.githubusercontent.com/4415419/32032168-69a70ca2-ba51-11e7-8e33-18edbcffe148.png)

Regardless the reproduction of this error, it's safe to say that the web standard for `<meta>` tags is to not include `</meta>` nor `/>`.

https://www.w3.org/TR/html5/document-metadata.html#the-meta-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

What do you think?

**Comment by damiencaselli** [comment]
Well, if you ask me I no longer use either of the closing tags.
I just realized this issue seemed to be related to `ember-cli-deploy-sentry`, not this repository 🙂

**Comment by Turbo87** [comment]
> I just realized this issue seemed to be related to ember-cli-deploy-sentry, not this repository 🙂

Indeed `ember-cli-sentry` does not add this meta tag at all, so please move this issue to `ember-cli-deploy-sentry` instead. Thanks! :)
