### ISSUE TITLE
raven service setup not called in development

### ISSUE THREAD

**Issue by sebastianhelbig** [damiencaselli/ember-cli-sentry#106]
Because of the early return (L14). What's the thought behind this?
https://github.com/damiencaselli/ember-cli-sentry/blob/bb85f46aeeecafc8b9aec32294559811078ad36a/app/instance-initializers/raven-setup.js#L10-L23

**Comment by Turbo87** [comment]
why would it be called if `development` is `true`?

**Comment by sebastianhelbig** [comment]
>why would it be called if development is true?

What else is the purpose of the `sentry.development` flag? Right now it does nothing.

**Comment by Turbo87** [comment]
I think the purpose is to disable `sentry` for development and testing

**Comment by sebastianhelbig** [comment]
With current beta this works as expected, no change needed anymore.
