### ISSUE TITLE
Support with Sentry's /ember file?

### ISSUE THREAD

**Issue by bauerjon** [damiencaselli/ember-cli-sentry#128]
There is this page https://sentry.io/for/ember/ which suggests you use

<script src="https://cdn.ravenjs.com/<VERSION>/ember/raven.min.js">
</script>

does this plugin play nicely with the `/ember/raven.min.js` ? or are these two separate implementations?

Also see https://docs.sentry.io/clients/javascript/integrations/ember/

**Comment by Turbo87** [comment]
those are two separate things. if you use this addon here it will automatically inject `raven.min.js` into your build pipeline.
