### ISSUE TITLE
Ember.onerror validation fails

### ISSUE THREAD

**Issue by jeffjewiss** [damiencaselli/ember-cli-sentry#129]
When adding this to an Ember 3.0 project it causes it to fail the `ember-qunit: Ember.onerror validation` test, which links to https://github.com/emberjs/ember-qunit/pull/304

Would adding:

```js
if (Ember.testing) {
  throw error;
}
```

to https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L178 fix the issue?

**Comment by Turbo87** [comment]
I'm surprised, because AFAICT https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L185-L187 should already take care of this 🤔 

We've been using the 3.0.0-beta.3 in production for quite some time and haven't had any issues with it so far.

**Comment by jeffjewiss** [comment]
Hmm, fair enough.

I have an app that was already updated to Ember 3 and I went to install install this addon, which was the only change, and I ran into the qunit validation error I mentioned above.

For now I've added:

```js
Ember.onerror = function (error) {
  if (Ember.testing) {
    throw error
  }
}
```

to the app.js so I could get Sentry working without broken tests, but I'm not sure what else could be causing the issue. 🤷‍♂️

**Comment by Turbo87** [comment]
can you reproduce this issue in a fresh `ember new` app?

**Comment by jeffjewiss** [comment]
I'll see if I can reproduce it on a fresh app.

I've had this happen on two personal Ember apps. One is private and one is public.

On the public one you can see that adding v3.0 of this addon breaks the build: [commit](https://github.com/jeffjewiss/jeffjewiss.com/commit/8390327a8a7ccb876a37d323842c7c42eba3b69f) - [build status](https://travis-ci.org/jeffjewiss/jeffjewiss.com/builds/352474109) and then adding the onError handler mentioned above fixes it: [commit](https://github.com/jeffjewiss/jeffjewiss.com/commit/98b5fcd3f9bfdc9a9c727ccfa26dc7650f040050) - [build status](https://travis-ci.org/jeffjewiss/jeffjewiss.com/builds/352484906).

**Comment by nickschot** [comment]
I also see this, but it doesn't seem to happen on every test run. I do not remember seeing it in the last beta.

**Comment by geoffreyd** [comment]
Adding this fixes the tests.
```
if (environment === 'test') {
  ENV.sentry.development = true;
}
```

**Comment by jeffjewiss** [comment]
@geoffreyd thanks for this!

The above seems like a good solution to the problem.
