### ISSUE TITLE
Support @sentry/node for FastBoot

### ISSUE THREAD

**Issue by mhluska** [damiencaselli/ember-cli-sentry#137]
Any plans to use `@sentry/node` to get error reporting working in FastBoot? I was finding this library just drops exceptions in the FastBoot environment but some errors only arise in that environment.

See https://github.com/getsentry/sentry-javascript/tree/master/packages/node

**Comment by Turbo87** [comment]
@mhluska in the long term that would be nice to have, yes. do you have time to work on that?

**Comment by Turbo87** [comment]
I'll close this as a duplicate of #77
