### ISSUE TITLE
Support for dataCallback option

### ISSUE THREAD

**Issue by damiencaselli** [damiencaselli/ember-cli-sentry#15]
As suggested by @hussfelt in PR https://github.com/damiencaselli/ember-cli-sentry/pull/14, `dataCallback` should be supported by the plugin.

A service registered before the plugin initializer might do the trick.

**Comment by hussfelt** [comment]
:+1: Tell me if you need anything :)

**Comment by hussfelt** [comment]
@damiencaselli maybe not needed at all:
https://github.com/getsentry/raven-js/blob/master/src/raven.js#L333-L343

Works for me!

**Comment by hussfelt** [comment]
Just needs a version-bump. :)

**Comment by damiencaselli** [comment]
@hussfelt this would indeed work with this specific version, so I'll consider this is not an issue anymore.

For the record, there was is a way to do this without upgrading to latest version, I'll push an example branch today to illustrate.

**Comment by hussfelt** [comment]
No worries!

Please do consider this closed, thanks!

**Comment by damiencaselli** [comment]
Using ravenjs version >= 1.1.19 solves this.
