### ISSUE TITLE
Capturing exceptions when development mode is true

### ISSUE THREAD

**Issue by lindyhopchris** [damiencaselli/ember-cli-sentry#17]
Thanks for the plugin - really useful!

In the readme, you state the application route should do the following if you want to trap routing errors:

``` js
actions: {
  error: function (err) {
    Raven.captureException(err);
  }
}
```

However, when development mode is `true`, this results in Raven console logging that Raven has not been configured.

I've tried this:

``` js
actions: {
  error: function (err) {
    if (Raven.isSetup()) {
       Raven.captureException(err);
    }
  }
}
```

but I still get the same message. Any ideas on how to detect whether Raven is usable?

**Comment by lindyhopchris** [comment]
One extra little thing. It might be worth mentioning in the readme that if you want to trap routing errors but still use the default Ember routing error sub-strate implementation, then you need to return true from the error action, i.e.:

``` js
actions: {
  error: function (err) {
    Raven.captureException(err);
    return true;
  }
}
```

as that caught me out for a while!

**Comment by damiencaselli** [comment]
Hi Chris,

I will add a mention about event bubbling in the README to avoid wasting time on this hehe

I'm taking a look at the `Raven.isSetup()` statement to avoid catching exception if Raven is not set.

**Comment by JohnRodney** [comment]
@lindyhopchris I saw the same behavior as well.  I was able to remedy this by adding `Raven.config('https://<key>@app.getsentry.com/<app>').install();` to the file that was logging the original messages.  Which in my case was the application.js route.

**Comment by lindyhopchris** [comment]
@JohnRodney thanks! however, I don't want the error to be logged to Sentry when debug mode is `true`. It's just that when debug mode is `true`, `Raven.captureException()` causes an error to the console which ideally would be avoidable if there was a way of checking Raven was not installed/knowing debug mode was active.

**Comment by damiencaselli** [comment]
@lindyhopchris You may want to have a look at the branch named [tsugi](https://github.com/damiencaselli/ember-cli-sentry/tree/tsugi).

Any call to Ravenjs is now done via an abstraction layer that let errors be thrown if no Raven object is defined (see https://github.com/damiencaselli/ember-cli-sentry/blob/tsugi/app/instance-initializers/raven-setup.js).

**Comment by damiencaselli** [comment]
Related to #16 

Next milestone will fix this problem.

**Comment by JohnRodney** [comment]
+1 thanks @damiencaselli
