### ISSUE TITLE
Explain dummy app in the README

### ISSUE THREAD

**Issue by pifantastic** [damiencaselli/ember-cli-sentry#19]
```
TypeError: Cannot read property 'enableGlobalErrorCatching' of undefined
```

Getting this error in the latest version (`2.0.0-beta.1`). Was not able to reproduce in the dummy app, unfortunately. I'm not sure why it's happening.

I've traced it as far as the `container.lookup()` in `raven-setup.js`. For some reason it returns `undefined` instead of instantiating the `service:logger` service.

I'll keep debugging, but figured I'd post in case it was something obvious to you.

**Comment by pifantastic** [comment]
Ah. I see. The dummy app has an `app/services/logger.js` that imports the raven logger. Should that be described in the README?

**Comment by damiencaselli** [comment]
Sorry about that, I felt like I was the only one to use the dummy app so I got lazy on that part hehe

I may add a quick note to the README.

**Comment by damiencaselli** [comment]
@pifantastic I've edited issue title and your first comment to reflect the change request.

**Comment by pifantastic** [comment]
Well it's not just a dummy app issue, right? Anyone using this in their apps will need to create an `app/services/logger.js` that exports the raven logger.

**Comment by damiencaselli** [comment]
You're totally right.

I mentioned this in the migration wiki page, but not in the README.

I'll correct this asap.
