### ISSUE TITLE
Raven methods should be runnable calling the logger service

### ISSUE THREAD

**Issue by damiencaselli** [damiencaselli/ember-cli-sentry#22]

**Comment by pifantastic** [comment]
That approach looks good. The only downside is that it "leaks" the abstraction making `logger` no longer a generic service. But that's not really all that big of a problem.

**Comment by damiencaselli** [comment]
I second that.

Another approach would have consisted of not implementing this abstraction and let the user explicitly wrap their code in a conditional statement like

```js
if (this.get('logger.isRavenUsable')) {
  /* Raven.setsomething() */
}
```

That also looked legit to me.

**Comment by damiencaselli** [comment]
Since it is working on latest beta tag, I consider this as done for now.
