### ISSUE TITLE
Add hook to allow filtering of exceptions

### ISSUE THREAD

**Issue by dschmidt** [damiencaselli/ember-cli-sentry#27]
Hey,

it would be nice if enableGlobalErrorCatching() would call a hook that can decide whether an exception should be logged or not.
Currently I need to copy the whole code to add a filter to get rid of reports 
https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L89

alternative:
https://raven-js.readthedocs.org/en/latest/config.html#shouldSendCallback

BR,
Domme

**Comment by dschmidt** [comment]
Something like this:

```
  enableGlobalErrorCatching() {
    if (this.get('isRavenUsable') && !this.get('globalErrorCatchingInitialized')) {
      const logger = this;
      let _oldOnError = Ember.onerror;

      Ember.onerror = function(error) {
        if(!logger.filterError(error)) {
          return;
        }

        logger.captureException(error);
        if (typeof _oldOnError === 'function') {
          _oldOnError.call(this, error);
        }
      };

      RSVP.on('error', (reason) => {
        if(!logger.filterError(error)) {
          return;
        }

        if (reason instanceof Error) {
          this.captureException(reason, { extra: {
            context: this.get('unhandledPromiseErrorMessage')
          } });
        } else {
          this.captureMessage(this.get('unhandledPromiseErrorMessage'), {
            extra: { reason }
          });
        }
      });

      this.set('globalErrorCatchingInitialized', true);
    }
  },
  filterError(error) {
    return true;
  }
```

**Comment by dschmidt** [comment]
and/or maybe something that lets you customize what actually get's logged.
The unhandled promise error message is not really useful in sentry whereas the name of the exception (if provided) might be much more useful.

The reason I'm coming up with this, is that I get a lot of TransitionAborted errors from Ember 2 (see https://github.com/emberjs/ember.js/issues/12505), here the error contains a name and seeing TransitionAborted in the sentry overview would already be much nicer if I choose to keep those assertions logged

**Comment by damiencaselli** [comment]
@dschmidt I've added this to `2.0.0-beta.5`.

If everything works, this will be the last addition to beta cycle.

**Comment by dschmidt** [comment]
Cool, I've been working on this a bit more in the last week, making ember data errors more useful and stuff like that... will publish what I have as soon as I'm ready..

**Comment by damiencaselli** [comment]
@dschmidt Did you have the chance to try beta 6 yet?
We could release v2 I guess.

**Comment by dschmidt** [comment]
Not beta6 itself, but my implementation of it is almost the same now - so I assume it is fine if you tested it ;-)
