### ISSUE TITLE
Automatically enable sourcemaps

### ISSUE THREAD

**Issue by wireframe** [damiencaselli/ember-cli-sentry#28]
ember-cli disables sourcemaps in production mode which makes sentry's stacktraces pretty much unusable.  It would be awesome to automatically enable sourcemaps with this addon so that stuff "just works".

If that's not possible or you'd want this to be an opt-in feature, it would be great to log a warning/error on startup that the deveoper needs to manually enable sourcemaps for sentry's stacktraces to be usable.

**Comment by hussfelt** [comment]
I had no idea about this. Explains why our new test-app with sentry is not tracked!
Probably saved me quite some debugging-time. Thanks! :+1:

**Comment by damiencaselli** [comment]
@wireframe I also had no idea about this.

I actually don't know how to do this, but I'll have a look into it. If you happen to know how to do this, feel free to submit a PR :christmas_tree:

**Comment by dschmidt** [comment]
Could be possible by the config hook of Ember Addon

**Comment by floqqi** [comment]
Just for the people who came here to look for a solution:

```javascript
// ember-cli-build.js

var app = new EmberApp(defaults, {
  sourcemaps: {
    enabled: true
  }
});
```

Will enable sourcemaps for every build (even production).

**Comment by damiencaselli** [comment]
🎉  if @floqqi's answer solves this.

**Comment by devinrhode2** [comment]
I included the `sourcemaps: true` option without testing that it was necessary, but in my sentry dashboard I do see stack traces with FULL function names, so I think it would be working.

**Comment by robclancy** [comment]
Why does the readme link to this issue instead of just saying to use sourcemaps directly?

**Comment by Turbo87** [comment]
@robclancy legacy. PRs welcome!
