### ISSUE TITLE
Log error to console on add-on initialize

### ISSUE THREAD

**Issue by tikijian** [damiencaselli/ember-cli-sentry#29]
Hi @damiencaselli 

I tried to setup this addon in my project but I end up with unconfigured Raven instance for some reason.

After a couple hours of investigation I found out that I copied wrong **dsn** from my Sentry account ( it was correct but contained *personal key* in it ). And Raven.js does not allow such dsn.
The thing is - this Raven.js error was suppressed by this try/catch block. 
https://github.com/damiencaselli/ember-cli-sentry/blob/master/app/instance-initializers/raven-setup.js#L35

Can you add more verbose error output in **catch** block ?
Something like ```console.warn(e);```

**Comment by damiencaselli** [comment]
Hi @tikijian, that's doable :+1:
