### ISSUE TITLE
Documentation does not mention the key 'config.sentry.version' which leads to improper configuration.

### ISSUE THREAD

**Issue by planetexpress69** [damiencaselli/ember-cli-sentry#30]
Also, config.sentry.cdn should only mention the server w/o any path or file...

**Comment by damiencaselli** [comment]
@planetexpress69 I wonder what version you are using, since this is documented in 1.13.1 and got removed in the 2.x beta cycle to avoid misleading configuration keys.

Have you checked the migration wiki entry (https://github.com/damiencaselli/ember-cli-sentry/wiki/Migration-from-1.x.x-to-2.x) ?

**Comment by planetexpress69** [comment]
Hello Damien,

I added 1.13.1 and pasted the whole config from  https://github.com/damiencaselli/ember-cli-sentry#complete-config <https://github.com/damiencaselli/ember-cli-sentry#complete-config>
This lead to garbled URL pointing to Raven because of ember-cli-sentry/config/index.js…

Documentation says: cdn: ‚//cdn.ravenjs.com/1.1.22/raven.min.js'
and does not mention ‚version‘ resulting in a URL like that
cdn.ravenjs.com/1.1.22/raven.min.js/undefined/ember,jquery,native/raven.min.js <http://cdn.ravenjs.com/1.1.22/raven.min.js/undefined/ember,jquery,native/raven.min.js>

Meanwhile I found your remarks in the migration notes. Still somewhat confusing as I did not migrate. Wasn’t using ember-cli-sentry before and started with a fresh Ember 2.2.0 project.

Sorry for bothering and thanks for your support!
Martin

**Comment by damiencaselli** [comment]
Hehe no problem, I guess the whole code upgrade was not quite clear, and though I try to keep doc in sync it may not always be easy to understand.

Thanks for your feedback!
