### ISSUE TITLE
Getting deprecation warning

### ISSUE THREAD

**Issue by devinus** [damiencaselli/ember-cli-sentry#34]
`DEPRECATION: Using `ApplicationInstance.container.lookup` is deprecated. Please use `ApplicationInstance.lookup` instead. [deprecation id: ember-application.app-instance-container] See http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container for more details.`

From this line: https://github.com/damiencaselli/ember-cli-sentry/blob/f377e28407384c72c1f40a24d7e0c8afc87e6c62/app/instance-initializers/raven-setup.js#L26

**Comment by damiencaselli** [comment]
@devinus Can this be fixed without breaking on ember 1.13.x?

Since I don't use ember 2 yet, @dschmidt can you please have a look at this?

**Comment by devinus** [comment]
Yeah, you just have to feature check.

**Comment by dschmidt** [comment]
I think it's as easy as

```
if(application.lookup) {
  service = application.lookup(...);
} else {
  service application.container.lookup(...);
}
```

**Comment by devinus** [comment]
Use this: https://github.com/rwjblue/ember-getowner-polyfill

**Comment by dschmidt** [comment]
ah that. yeah.

**Comment by panthony** [comment]
This issue broke my ember 1.13.x application which is a shame because I'd like to upgrade to the latest sentry SDK  :(

> Uncaught TypeError: application.lookup is not a function
