### ISSUE TITLE
Better first usage experience

### ISSUE THREAD

**Issue by stravid** [damiencaselli/ember-cli-sentry#35]
First of all, thanks for creating this addon! I never used it before so my experience while setting it up is still fresh. I did following steps to get going:

1. Install the addon.
2. Install the raven-js dependency via Bower.
3. Import the raven-js dependency.
4. Create the raven service.
5. Modify the CSP rules.
6. Setup the config so it does not track in development build.
7. Setup the config so it tracks in production builds.

Steps 2, 3 and 4 could be done by the addon itself when it's installed. This would simplify the getting started process for beginners significantly.

Are you open for a pull request implementing this?

**Comment by damiencaselli** [comment]
Hi @stravid, thanks for the feedback.

I'd appreciate very much a PR for this, I hardly ever use ember these days.

Concerning step 4, I've intentionally left this step manual in case someone already have their own service they want to integrate raven to, but I think this almost never happens anyway.

Any idea about it? @dschmidt

**Comment by dschmidt** [comment]
Yeah, dunno, seems rather esotheric if someone can't use a default service. I provide one in ember-cli-deploy-sentry

**Comment by damiencaselli** [comment]
#36 fixes the first steps.

**Comment by damiencaselli** [comment]
Hi @stravid, some of the tasks you mentioned were completed, but I'd gladly accept PR for the 4th one :wink:
