### ISSUE TITLE
Attempting to inject an unknown injection: `service:raven`

### ISSUE THREAD

**Issue by SashaBorandi** [damiencaselli/ember-cli-sentry#40]
Uncaught Error: Attempting to inject an unknown injection: `service:raven`

**Comment by damiencaselli** [comment]
Well, you seem to be attempting to inject an unknown injection... :trollface: 

Did you create the service using the generator command?

**Comment by floqqi** [comment]
Had the same problem. Didn't know that generating a logger using `ember g logger raven` is mandatory.

Two solutions for this:
1. Update the README (especially the TLDR section)
2. Make a default `raven`-service, so nobody needs to generate one if he isn't interested in changing something in the default one

**Comment by damiencaselli** [comment]
Running that command is not mandatory, but having a service that will be called is mandatory (one can have their own logger).

This is mentioned at least twice in the README, but it may seem obvious to me since I'm the author.

@floqqi would you please let me know or suggest improvements in the README file?

**Comment by floqqi** [comment]
But why do I need to implement an own service which only does `this._super(...arguments)` on every method? Wouldn't it be a better solution to inject the `RavenLogger` as a service by default?

**Comment by damiencaselli** [comment]
The generator enables easy method overriding for users by exposing some methods, hence the `this_super(...arguments)` in the default generated service.

Declaring a one-line service with `export { default } from 'ember-cli-sentry/services/raven';` does the trick, and may be generating should be as concise as that; I think exposing public methods in the generator allows better understanding of the service.

This is, for instance, what `ember-simple-auth` used to do, and this plugin could follow the same path if enough people ask for it :smiley:

**Comment by tavosansal** [comment]
I encountered this problem as well. I think the readme could be improve by saying something like this:

_If you create a logger using the ```ember g logger <logger-name>``` then in the configuration for sentry you must set this as the ```serviceName: <logger-name>``` property._

Something similar to that would have done it for me.

Thanks!

**Comment by GCorbel** [comment]
I had the same problem. It works with `ember g logger raven`.
