### ISSUE TITLE
Instance initializer not calling install

### ISSUE THREAD

**Issue by mapohjola** [damiencaselli/ember-cli-sentry#41]
When setting up raven in the instance-initializer we are not calling .install()

Should `window.Raven.config(dsn, ravenConfig);` not be `window.Raven.config(dsn, ravenConfig).install();` like in the install documentation https://docs.getsentry.com/hosted/clients/javascript/install/ 

When not calling .install() I am not getting window.onerrors logged to sentry.

**Comment by damiencaselli** [comment]
I am not sure to understand your issue here.

Both `config` and `install` methods are called in the instance initializer, see https://github.com/damiencaselli/ember-cli-sentry/blob/master/app/instance-initializers/raven-setup.js#L28-L42

**Comment by mapohjola** [comment]
Sorry I must be blind.

**Comment by damiencaselli** [comment]
:sunglasses:
