### ISSUE TITLE
Integrate User Feedback Dialog

### ISSUE THREAD

**Issue by ColtonProvias** [damiencaselli/ember-cli-sentry#46]
New feature in Sentry 8.4.  Documented at: https://docs.getsentry.com/on-premise/learn/user-feedback/

**Comment by damiencaselli** [comment]
I think this is up to the user to implement this. I can't assume everyone wants to use it and make it the default behaviour.
However, if most of the ember-cli-sentry users want this implemented as an option, I'll gladly do it 👍 

This add-on purpose is to ensure Sentry is properly set up, and make errors easy to manipulate before sending them to the Sentry servers. It also tries to remain as user-pref agnostic as possible.

For anyone looking to implement this, it can be achieved by overriding the [`captureException` method](https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L51-L64).
