### ISSUE TITLE
Raven catches everything in console, not sure how to disable?

### ISSUE THREAD

**Issue by grapho** [damiencaselli/ember-cli-sentry#48]
after installing `ember-cli-sentry` and configuring the `Raven.js`.  I have noticed that almost all error logs and console logs are called through raven now and it is hard to locate where the message originates from?

For example if i were to put a `console.log('hello')` into one of my model hooks.  when i view the output in developer console, the source of the log comes from raven.js now.. throughth a wrapMethod function.. now i can no longer see where my console log is coming from...

I know that this is a raven issue primarily.. but i cant find any docs here or in sentry/raven that describe how i can disable this? or how I could possible use it to my advantage?  I am hoping soeone here has encountered it an knows the answer?

**Comment by kkumler** [comment]
@grapho What version of Raven are you using with this?

**Comment by grapho** [comment]
@kkumler the latest cdn 3.0.4 it looks like

**Comment by damiencaselli** [comment]
Hi @grapho 

It seems Raven.js now wraps every `console` method : https://github.com/getsentry/raven-js/blob/master/src/raven.js#L931-L935

I doubt you can disable it, and may be sticking to the 2.x version might be wise for a bit, though that doesn't really solve to your problem.

**Comment by grapho** [comment]
yeah i was afraid of that.. however there appears to be some api in that code that suggests i can use it to my advantage somewhere somehow.

thanks for the responses!

**Comment by damiencaselli** [comment]
If you happen to solve that, would you mind leaving a message here in case someone else encounters the same issue?

**Comment by grapho** [comment]
will do

**Comment by grapho** [comment]
here is a minor update.

Raven swallows up all the console methods so it can generate it's [breadcrumbs](http://blog.getsentry.com/2016/05/04/breadcrumbs.html) .. which i can see might be helpful in some scenarios, but ember build likes to strip out console logs in production mode, so it losses some sparkle for me.

Based on [the issue I reported](https://github.com/getsentry/raven-js/issues/584) the raven people seem open to introducing a flag to disable the behavior or introduce a raven.log() to replace the lost functionality

**Comment by grapho** [comment]
Another Update:

This might possibly close this issue entirely.

I just discovered that `ENV.sentry.development = true` in `config/envireonment.js` is the answer... as I was concerned about using raven.js in a development setting.. which is not the correct use case.  Why in ember dev mode would i want to pass errors to sentry? I would only want that in a production app...

anyway, setting development mode to `true` disables raven client entirely, which brings the console.log() methods back to js console.. and all my other console error messages bac to js console.

@damiencaselli my question to you is:  `development` property in the `config/environment.js`.. is that an addon flag to bypass raven? or is it part of the raven.js config setting?  knowing this will allow me to close one or the other or both github issues i posted.

**Comment by damiencaselli** [comment]
That property is documented in the README, but may not be quite clear:

> If set to true, this add-on will never initialize
> Raven object and capturing will be handled by the logging service (redirected to the console if you use default service).

See this: https://github.com/damiencaselli/ember-cli-sentry/blob/master/app/instance-initializers/raven-setup.js#L10-L15

Setting `development: true` will prevent Raven.js to be initialized, and will use `console.log` instead of Raven.

**Comment by grapho** [comment]
@damiencaselli  yep that is the one.. the readme comment there was not 100% clear to me, which is why I avoided it at first... I think it is the very first line that made me avoid it the most.

THe clarification you provided ( I believe ) should be the test for the readme

> Setting development: true will prevent Raven.js from being initialized. Errors and logs will log to the console instead of being reported by Raven.

That sounds a little more clear to me

**Comment by damiencaselli** [comment]
@grapho can you tell me if a26b7af makes it more clear to you?

**Comment by grapho** [comment]
@damiencaselli that looks great!

On a side note, unrelated, what does the `debug` option do? can we explain that a little better?  ... actually i think that is acutally a raven.js feature.. but raven is not the best documented library either :p

**Comment by damiencaselli** [comment]
@grapho it is indeed the Raven option, that has to be be provided when Raven is instantiated.

**Comment by HelloMihai** [comment]
@damiencaselli the link you posted is showing the latest version of the file.  Corrected link if anyone is confused:

https://github.com/getsentry/raven-js/blob/b311690ec90f8a319527a24b28b880dedbe7b848/src/raven.js#L931-L935
