### ISSUE TITLE
Can't use regex values for ignore/whitelist URLs

### ISSUE THREAD

**Issue by batjaa** [damiencaselli/ember-cli-sentry#49]
It looks like ember config/environment.js ENV object only allows object and string values. Results raven install to misinterpret regex values.

Here's a repro for ember not getting regex from config file. https://github.com/batjaa/test-config-regex

**Comment by damiencaselli** [comment]
This is more likely a problem concerning ember-cli.
Do you mind creating an issue on their repository and link it to this one?
