### ISSUE TITLE
Cannot configure Raven unless already setup

### ISSUE THREAD

**Issue by panthony** [damiencaselli/ember-cli-sentry#56]
Unless the `install` method has been called on the Raven object, all call to `callRaven` are dropped.

It means that we can't set either tag's context, user context, etc..

In my case, the init on the application route is called before install is call on the Raven service thus ignored.

The only methods that needs the Raven service to be setup are captureMessage/captureException really.

**Comment by damiencaselli** [comment]
This behaviour can be easily overridden in your own service definition.

See: https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L147-L155

**Comment by panthony** [comment]
That's what I done in the end, I was just thinking it would be nice that it works OOTB
