### ISSUE TITLE
Best way to add context to error reports?

### ISSUE THREAD

**Issue by swquinn** [damiencaselli/ember-cli-sentry#58]
First, thanks for this addon. I was beginning to gear up to write my own addon for Sentry integration before finding this and thought I'd give this a try before rolling my own.

I do have a question though, and it surrounds tagging and adding context to errors being reported to Sentry. If I wanted to add a user context to the errors, Sentry's [documentation](https://docs.sentry.io/hosted/clients/javascript/#adding-context) suggests doing something like the following:

```javascript
Raven.setUserContext({
    email: 'matt@example.com',
    id: '123'
})
```

I'm not sure necessarily how to go about this with your addon. Would it be correct to extend `ember-cli-sentry/services/raven` to add this in? If you could provide some guidance on this matter, I'd really appreciate it.

Thanks!

**Comment by damiencaselli** [comment]
Hi @swquinn, an example is worth a thousand words, the dummy application shipped with tests does exactly what you want: https://github.com/damiencaselli/ember-cli-sentry/blob/master/tests/dummy/app/routes/application.js#L8

Basically the add-on offers a safe proxy to interact with Raven by trying to call a Raven.js method (`callRaven()`) if it is useable – the default being Raven.js initialization successful –, or else do nothing.
You can also easily override these default behaviours by extending the service and implementing rules the way you want.

Cheers!

**Comment by swquinn** [comment]
Awesome! I hadn't even thought about looking in the dummy application for an example. Thanks for pointing that out!

**Comment by devinrhode2** [comment]
How I ended up getting this done:
https://stackoverflow.com/questions/48329217/ember-sentry-raven-set-user-context-when-user-model-loads
