### ISSUE TITLE
Parse RegExp in whitelist urls

### ISSUE THREAD

**Issue by damiencaselli** [damiencaselli/ember-cli-sentry#62]
@gabz75 did it for `ignoreErrors` in #51, we could stretch the extra mile and make it work for the `whitelistUrls` option.

Relates to #49

**Comment by kmiyashiro** [comment]
Can we please merge this? This currently makes whitelistUrls unusable if you have a dynamic filename (cache busting).

**Comment by kmiyashiro** [comment]
Nevermind, I think the current RegExp parsing in #51 is confusing and possibly harmful.

**Comment by damiencaselli** [comment]
Resolved by #83
