### ISSUE TITLE
Uncaught promises logged twice to Sentry

### ISSUE THREAD

**Issue by jessepollak** [damiencaselli/ember-cli-sentry#64]
We're using this library and it seems to log uncaught promises twice to Sentry. Once, in `Ember.onerror` and once in `RSVP.on('error', ...)`. When it's logged through `Ember.onerror`, it also incorrectly calls `caputreExcpetion` with the reason object, which is not an error -- leading to it just being logged as `[object Object]`. 

Has anyone else dealt with or seen this?

**Comment by damiencaselli** [comment]
Hi @jessepollak 
I haven't seen this behavior, but I'll run some tests on a blank ember application and let you know if that happens.

**Comment by jessepollak** [comment]
Thanks @damiencaselli! Let me know if there's anything I can do to help :)

**Comment by damiencaselli** [comment]
Hi @jessepollak, are you still encountering the duplication problem?

**Comment by jessepollak** [comment]
Nope, will close!

**Comment by damiencaselli** [comment]
@jessepollak Can you tell what solved this btw?

**Comment by jessepollak** [comment]
I stopped maintaining the Ember project that had the issue 😬

**Comment by damiencaselli** [comment]
Golden 🥇
