### ISSUE TITLE
Safe to upgrade to Raven 3.9.x?

### ISSUE THREAD

**Issue by benoror** [damiencaselli/ember-cli-sentry#69]
Would it be safe to upgrade to latest minor version of Raven (currently `3.9.x`)?

<img width="1002" alt="screen shot 2017-01-19 at 10 51 32" src="https://cloud.githubusercontent.com/assets/119117/22116215/68a2521a-de35-11e6-8ea6-83f0371827c9.png">

https://docs.sentry.io/clients/javascript/

- [ ] Change blueprint https://github.com/damiencaselli/ember-cli-sentry/blob/ed0360a2aff6399b2fa791b211777f2a1c1740bc/blueprints/ember-cli-sentry/index.js#L10

**Comment by damiencaselli** [comment]
@benoror I think so, this add on is made to work on a wide variety of Raven versions.

**Comment by damiencaselli** [comment]
Refer to #71 for closing reason.
