### ISSUE TITLE
Remove "serviceName" option and add service to app by default

### ISSUE THREAD

**Issue by Turbo87** [damiencaselli/ember-cli-sentry#82]
I would like to propose the deprecation of the `serviceName` option. To me it seems very confusing and I don't actually see any advantage of making it configurable since it seems very unlikely that someone actually has another unrelated `raven` service in his app.

If we remove the `serviceName` propery and rely on it always being `raven` we can also add the service to the `app` folder so that everyone has it by default and only those that want to override certain things will need to generate one for themselves.

This is obviously a breaking change, but IMHO it is a useful one.

**Comment by marcoow** [comment]
ESA used to have this as well but it adds a bunch of (unnecessary) complexity to the system. You could always do this in an app anyway:

```
//app/services/my-raven-whatever.js
import Service from 'ember-cli-sentry/services/raven';

export default Service.extend();

```

**Comment by Turbo87** [comment]
@marcoow sure, but `session` is a lot more common as a service name compared to `raven`

**Comment by marcoow** [comment]
Yes, just saying there's a cleaner way to redefine the service with a different name anyway.

**Comment by Turbo87** [comment]
@marcoow yeah, but then you would need to pass that custom service name to the initializer and then we're back in the mess we're in right now 🤷‍♂️

**Comment by marcoow** [comment]
The thing is you're opting in to that mess than as opposed to now where you always have to deal with `serviceName`.

**Comment by damiencaselli** [comment]
@marcoow the funny part of this is I learned add-on scaffolding by digging `ESA` source 👨‍🎓 
BTW Thanks for the work on this add-on.

Anyway, the `serviceName` sole purpose was to allow people switch from a logger to another without search-and-replacing the whole code. Use __LoggerA__ one day, use __raven__ the other one by only changing the code in the logger.

However, if this option isn't used at all (I have absolutely no feedback beside what is written on GitHub), I'm fine with changing the way it is handled, or even ditch it.

May be the way ESA scaffold could be replicated here, it is quite solid and I think the project has enough users to know if it's the good way to do it or not 😃
