### ISSUE TITLE
Add vendor shim for `raven`

### ISSUE THREAD

**Issue by Turbo87** [damiencaselli/ember-cli-sentry#84]
Whether we import raven-js from bower, npm or CDN we always have to deal with `window.Raven`. It would be great if we could just include a vendor shim so that we could `import Raven from 'raven';` instead of using the global.

**Comment by damiencaselli** [comment]
I think it is related to #81

**Comment by Turbo87** [comment]
@damiencaselli no, it's unrelated. vendor shims work fine for bower dependencies too.

**Comment by damiencaselli** [comment]
@Turbo87 can you confirm `3.0.0-beta` solves this?
https://github.com/damiencaselli/ember-cli-sentry/blob/3.0.0-beta/vendor/raven-shim.js

**Comment by Turbo87** [comment]
yep, resolved by #81
