### ISSUE TITLE
Unit tests for objects that use sentry never work

### ISSUE THREAD

**Issue by RobinDaugherty** [damiencaselli/ember-cli-sentry#86]
(This may be specific to Mocha, not sure.)

When this addon is used properly, it injects the `raven` service into all controllers, models, etc. And properly using raven, these should call `get('raven').captureException` and similar in order to report on failures or whatever.

However, in Mocha unit tests for these controllers, models, etc., the app's initializers are not run, so the `raven` property is never set up. This causes all code like this:

```js
export default Ember.Controller.extend({
  validateCredentials(email, password) {
    return new Ember.RSVP.Promise((resolve, reject) => {
      this.get('session').authenticate('authenticator:oauth2', email, password)
      .then(() => {
        resolve();
      }, () => {
        this.set('errorMessage', 'Invalid credentials');
        reject();
      }).catch((error) => {
        this.set('errorMessage', 'Sorry, there was a problem checking credentials.');
        this.get('raven').captureException(e);
        reject();
      });
    });
  },
});
```

to fail in any unit test because `raven` is undefined.

I tried [adding it to the test helper](https://stackoverflow.com/a/31508198/1589422) but the raven initializer still never gets called.

I also tried injecting the raven service directly into the controller with:

```js
export default Ember.Controller.extend({
  raven: Ember.inject.service('raven'),
});
```

and then adding it to the unit test's `setupTest`, and this worked, but it also means that I have to bypass ember-cli-sentry in every model, controller, etc.

Any ideas on how to best utilize ember-cli-sentry while also supporting unit tests?

**Comment by backspace** [comment]
Is it possible you have to add `needs: ['service:raven']` somewhere? I haven’t used Mocha for Ember testing for a long time but it’s probably required in some way like with QUnit in [the documentation](https://guides.emberjs.com/v2.15.0/testing/testing-controllers/#toc_testing-controller-needs).

**Comment by RobinDaugherty** [comment]
Yes, I wasn't clear in my description, but in some cases these were integration tests (which don't have a `needs` argument), and in others we would add it to `needs`. The problem seems to be that the `raven` service is simply not injected when tests are being run.

Also, I found out more recently that [`captureException` and `captureMessage` _cause an exception to be raised_ if Raven is disabled](https://github.com/damiencaselli/ember-cli-sentry/blob/master/addon/services/raven.js#L147). So any path where an exception or any message is reported to raven is impossible to test, and will raise an exception in production if raven is disabled for any reason.

So my issue here is about ember-cli-sentry not being compatible with a TDD process.
