### ISSUE TITLE
How to prevent some types of errors from being reported

### ISSUE THREAD

**Issue by rstudner** [damiencaselli/ember-cli-sentry#92]
I must be doing something wrong :)

```js
    if (isPresent(recordId)) {
      try {
        get(this, 'store').findRecord('customer-device', recordId, { reload: true }).then((customerDevice) => {
           console.log(get(customerDevice, 'status'));
        });
      } catch(err) {
        console.debug(err);
      }
    }
```

In the use case that findRecord returns a 404, I CANNOT seem to prevent that 404 from being reported to sentry.

I have it in a try catch / not sure what further I need to do.

(in this case it is doing a 404 because the current user doesn't have permission to see the record, and we are doing a 404 vs a 403)

**Comment by RobinDaugherty** [comment]
@rstudner `findRecord` returns a promise, and you need to add a `catch` call to the promise in order to catch errors that occur with it. Adding a `try` block around a call like this won't do the job.

```js
  this.get('store').findRecord('customer-device', recordId, { reload: true }).then((customerDevice) => {
    console.log(get(customerDevice, 'status'));
  }).catch((failure) => {
    if (failure.errors && failure.errors['404']) {
      this.get('raven').captureMessage("An exception occurred but I don't want it reported as a failure.");
    } else {
      throw(failure);
    }
  });
```

If you're using an older version of Ember, or other (older) Promise libraries, you might not have a `catch` method, in which case you pass two functions to the `then` function.

```js
  this.get('store').findRecord('customer-device', recordId, { reload: true }).then((customerDevice) => {
    console.log(get(customerDevice, 'status'));
  }, (failure) => {
    if (failure.errors && failure.errors['404']) {
      this.get('raven').captureMessage("An exception occurred but I don't want it reported as a failure.");
    } else {
      throw(failure);
    }
  });
```

Welcome to the world of asynchronous Javascript, it's not straightforward or obvious!

**Comment by rstudner** [comment]
Yeah, my chief mistake was the try/catch vs the .catch.  This seems to get me every tuesday haha

The other thing I don't get (this is specific to this library/implementation).. is why the this.get('raven').captureMessage and .captureException will themselves throw errors in development mode.

(thus, I have to put my this.get('raven') things inside their OWN try catches, to use the default raven service in development :)

**Comment by RobinDaugherty** [comment]
@rstudner rather than that try/catch block, you can use [this workaround](https://github.com/damiencaselli/ember-cli-sentry/pull/97#issuecomment-333730424).

**Comment by Turbo87** [comment]
closing as the original question seems to be answered
